### ISSUE TITLE
Menu of website more detailed

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/ABACBS2020_tidytranscriptomics#11]
@mblue9 do you think is possible to make the website menu, maybe with some option?

![image](https://user-images.githubusercontent.com/7232890/100185184-56267600-2f37-11eb-89c9-7214b43aef56.png)

more detailed such as in Rstudio

![image](https://user-images.githubusercontent.com/7232890/100185164-44dd6980-2f37-11eb-8537-f0a19f0566d7.png)

**Comment by mblue9** [comment]
We might be able to by adding toc: depth to the pkgdown file, see here https://github.com/r-lib/pkgdown/pull/821/files

**Comment by mblue9** [comment]
Trying depth of 4 here https://github.com/stemangiola/ABACBS2020_tidytranscriptomics/commit/d1e9205cfe91f513aee686f5a700e8a4008e7657

**Comment by mblue9** [comment]
Dammit it doesn't work and now I remember we already encountered this a few months ago :( https://github.com/r-lib/pkgdown/issues/1357
The website will only show depth of 2 so we can either
1. write some javascript to hack around it to show more depth, as mentioned in that issue (but I don't know javascript)
2. separate out into Part2a/b/c e.g.

```
 # Part 2a tidyseurat single-cell analysis
     ## Subheadings
 # Part 2b Pseudobulk analysis
    ## Subheadings
 # Part 2c tidySingleCellExperiment single-cell analysis
   ## Subheadings
```
3. leave as is

What do you prefer?

**Comment by stemangiola** [comment]
Thanks Maria,

let's leave it. no problem
