### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by mblue9** [stemangiola/ABACBS2020_tidytranscriptomics#3]
Some todos

- [x]  For Rpharma we did 2/3  of workshop on bulk, 1/3 single cell, if we think this audience will be more interested in single cell we could do 1/3 bulk (e.g. short version like biocasia) and 2/3 single cell? -  1/2 bulk and 1/2 single-cell
- [x]  Are we just going to use tidyseurat like RPharma? Or tidySingleCellExperiment aswell? Current workshop description mentions tidySCE so should prob update that https://www.abacbs.org/workshops - will use both
- [x]  Decide what changes we want to add from most recent workshop (BiocAsia) https://github.com/stemangiola/biocasia2020_tidytranscriptomics - add the shortened version of comparing diff exp tools, remove pasilla and long exercises (better to have short poll qus interspersed) and add tidySingleCellExperiment for comparison with tidyseurat 
- [x]  Do we need to get written permission to use ABACBS logo on workshop page? As it says here https://www.abacbs.org/logos (have contacted to ask & was sent the logo)
- [x]  Decide what package versions we'll use for tidybulk etc, at the moment we're using the same as the RPharma workshop so should prob at least update to more current

Stefano
- [x] Add pseudobulk section
- [ ] Update the[ roadmap figure](https://github.com/stemangiola/tidytranscriptomics/) (remove tidySE and tidySCE)
- [ ] (Not essential) example of base R vs tidyseurat e.g. left_join, inner_join, sampling

Maria
- [x] Add biocAsia parts to workshop for bulk and single-cell
- [x] git pull updated workshop material to RStudio server and retest
- [x] Turn on Docker build
- [ ] Send reminder email to attendees with Zoom link and material

Whoever gets to it
- [x] Create polls for single cell section

**Comment by stemangiola** [comment]
>     * if we think this audience will be more interested in single cell

Good question



>     * Are we just going to use tidyseurat like RPharma

I don't have strong preferences. I think Seurat is more used but requires a bit more work of copy/paste on our side. (we will mention tidyseurat and tidySingleCellExperiment work exactly the same, and that is the beauty!)



>     * Decide what package versions we'll use for tidybulk etc

I think the ones in the official repos are fine. Also the current in github are also fine.

**Comment by mblue9** [comment]
Ok cool, I jut tried installing using current versions but doesn't work for tidyseurat as it's still not back in cran :( have you had any update on when it might get back in?
```
Downloading GitHub repo stemangiola/ABACBS2020_tidytranscriptomics@HEAD
tidyHeatmap (NA -> 1.1.5) [CRAN]
tidygate    (NA -> 0.2.8) [CRAN]
tidybulk    (NA -> 1.2.0) [CRAN]
Skipping 1 packages not available: tidyseurat
Installing 4 packages: tidyHeatmap, tidyseurat, tidygate, tidybulk
Error: package ‘tidyseurat’ is not available for this version of R
```

**Comment by mblue9** [comment]
Actually I may just stick with installing the specific version from github like we did before i.e. 
"stemangiola/tidybulk@v1.2.0", "stemangiola/tidygate@v0.2.8", "stemangiola/tidyHeatmap@v1.1.5")

Are you able to make a tagged release for tidyseurat that has the recent fixes? and I'll install that?
 "stemangiola/tidyseurat@vx.x.x",

**Comment by stemangiola** [comment]
> Are you able to make a tagged release for tidyseurat that has the recent fixes?

Sure. Tonight I will get it done.
